### ISSUE TITLE
[BUG]: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon

### ISSUE THREAD

**Issue by derskythe** [dethlex/NumberConverter#10]
Hi, I often get exceptions. I think that your plugin will soon stop working completely if JetBrains says: deprecated.

### Exception

```java
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.dethlex.numberconverter.ConvertActionGroup$Bin' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.dethlex.numberconverter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

<details><summary>System config</summary>
<p>

```
CLion 2024.1
Build #CL-241.14494.288, built on April 5, 2024
Subscription is active until August 13, 2024.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.1.0-20-amd64
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
  actionSystem.update.actions.warn.dataRules.on.edt=false
  ide.balloon.shadow.size=0
  debugger.click.disable.breakpoints=true
  debugger.attach.dialog.enabled=true
  documentation.show.toolbar=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  ide.slow.operations.assertion=false
  terminal.new.ui=true
Non-Bundled Plugins:
  com.intellij.datagen (241.14494.150)
  org.editorconfig.editorconfigjetbrains (241.14494.150)
  lermitage.intellij.extratci (1.35.0)
  intellij-awk (0.4.3.1)
  MultiHighlight (3.1.0)
  de.netnexus.camelcaseplugin (3.0.12)
  org.jetbrains.plugins.go-template (241.14494.150)
  com.markskelton.one-dark-theme (5.10.0)
  com.jetbrains.naming-is-hard (1.5.0)
  String Manipulation (9.12.0)
  com.github.johnthagen.cppcheck (1.6.5)
  lermitage.intellij.extra.icons (2024.3.4)
  com.wakatime.intellij.plugin (14.3.13)
  com.intellij.plugin.adernov.powershell (2.6.1)
  GrepConsole (12.25.0-IJ2023.3)
  com.intellij.grazie.pro (0.3.298)
  nl.rubensten.texifyidea (0.9.4)
  com.dethlex.numberconverter (2.0.0)
  com.intellij.ml.llm (241.14494.320)
  com.github.copilot (1.5.2.5345)
  com.ld.gitlab (2.6.4)
  zielu.gittoolbox (500.2.3+233)
  com.github.blarc.gitlab-template-lint-plugin (1.13.2)
  artsiomch.cmake (241.1.0)
  artsiomch.cmake.plus (241.1.0)
Current Desktop: KDE
```

</p>
</details> 

<details><summary>Screenshot</summary>
<p>

![image](https://github.com/dethlex/NumberConverter/assets/31771569/87b7f71b-03a1-4639-ab63-d72407e304b7)

</p>
</details>

**Comment by dethlex** [comment]
@derskythe thank you, going to fix it
